### ISSUE TITLE
Set and retrivie Enviroment variables at terminal for Vue use in dev mode.

### ISSUE THREAD

**Issue by alexsandro-xpt** [vuejs-templates/webpack-simple#106]
In looking for this feature but there are no documentation about that in https://vuejs-templates.github.io/webpack/env.html

I would to read enviroment variables declared in my terminal for Vue Dev Mode when I run `npm run dev`. If there no defined var in that, so then, Vue Dev Build shoud get the static value setted in the `dev.env.js`.

There way to do that?

**Comment by LinusBorg** [comment]
You can simply copy that behaviour from the webpack template. Look at the dev & prod webpack configs, there those env files are passed to the `DefinePlugin`

For further help you should join the forum.vuejs.org

**Comment by Dean-Christian-Armada** [comment]
I think this is very important especially docker and jenkins builds are getting popular nowadays. Can you like give an example of how to do this? Or more importantly, is it even possible to do this at this point of time. It's so useful if the setting of environments is extendable to that of Linux and Shell environments to make it more dynamic.

**Comment by LinusBorg** [comment]
If the documentation of the [DefinePlugin](https://webpack.js.org/plugins/define-plugin/) isn't enough for you, that's a question  better suited for forum.vuejs.org
