### ISSUE TITLE
How to add local fonts?

### ISSUE THREAD

**Issue by brickgale** [vuejs-templates/webpack-simple#109]
Trying to add local fonts on `src/assets/fonts` but i got an error that says module parse failed and says you may need an appropriate loader to handle this file type. Do i need to change webpack config for this?

**Comment by eyalcohen4** [comment]
@brickgale Would love to know how you ended loading fonts

**Comment by brickgale** [comment]
@eyalcohen4 i think i just added the extensions on `webpack.config.js`. See sample commit: https://github.com/brickgale/brickgale.github.io/commit/961a37cf3411aa8afdbaf5efd8eec65f10e6aa40
