### ISSUE TITLE
h1 msg is missing?

### ISSUE THREAD

**Issue by dtsao** [vuejs-templates/webpack-simple#117]
I have vue-cli 2.8.2 installed on Windows 10. When I run:
`vue init webpack-simple testfolder`

then look at testfolder\src\App.vue, I see:

```
<template>
  <div id="app">
    <img src="./assets/logo.png">
    <h1></h1>
    <h2>Essential Links</h2>
...
````

instead of:
```
<template>
  <div id="app">
    <img src="./assets/logo.png">
    <h1>{{ msg }}</h1>
    <h2>Essential Links</h2>
...
```

`{{ msg }}` is missing in the h1 tag.

I think https://github.com/vuejs-templates/webpack-simple/commit/f7e0de88667be9aef74a16acf04e62cfcc475ba7#diff-b882e31e260094ddfa4517cb41fc5277 should have fixed this, but it seems like vue-cli is not getting the current version of this file.

**Comment by LinusBorg** [comment]
Actually, this commit is repsonsible for the behviour you are seeing. It removed the escape character to keep vue-cli from interpreting this as a handlebars interpoliation. I'll fix it.

**Comment by LinusBorg** [comment]
Should work now.

**Comment by dtsao** [comment]
Thanks, looks good.
