### ISSUE TITLE
beforeDestroy, destroyed triggers after created in hot reload

### ISSUE THREAD

**Issue by Lacroute** [vuejs-templates/webpack-simple#123]
Hi,

I was experiencing some weird behavior with my fresh install of this template. The `created` hook  was triggered before the `beforeDestroy` and `destroyed`. But the real problem is `beforeDestroy` and `destroyed` wasn't triggered in the first hot reload at all.
Also, the `created` hook is triggered too soon.

Step to reproduce:

1. `vue init webpack-simple`
2. edit the `App.vue` file
```
<script>
export default {
  name: 'app',
  data () {
    return {
      msg: 'Welcome to Your Vue.js App'
    }
  },
  created () {
    console.warn('created', Date.now())
  },
  mounted () {
    console.warn('mounted', Date.now())
  },
  beforeDestroy () {
    console.warn('beforeDestroy', Date.now())
  },
  destroyed () {
    console.warn('destroyed', Date.now())
  }
}
</script>
```
3. Re-edit to force hot reload
4. compare

Screen of my console:
![capture d ecran 2017-08-04 a 15 48 21](https://user-images.githubusercontent.com/3015073/28971645-fbdc87f2-792c-11e7-8e41-fde6891475a0.png)

**Comment by Lacroute** [comment]
And a repo to see the bug > https://github.com/Lacroute/webpack-simple-bug

**Comment by LinusBorg** [comment]
If this is a bug, it belongs in the vue main repository, not here.
