### ISSUE TITLE
Webpack configuration to load handle css files ins webpack-simple template

### ISSUE THREAD

**Issue by laobanbr** [vuejs-templates/webpack-simple#125]
Hello,
On  main.js i was trying to import a css framework as such
```
import Buefy from 'buefy'
import 'buefy/lib/buefy.css'
```

And terminal was showing 
```
Module parse failed: /home/re/Projects/code-along/node_modules/buefy/lib/buefy.css Unexpected character '@' (2:0)
You may need an appropriate loader to handle this file type.
```

The fix was to include style-loader
`npm install style-loader --save-dev`

And modify webpack.config.js adding
```
{
    test: /\.css$/,
    loader: "style-loader!css-loader"
},
```

I do not know how to submit this changes to the repository, so I am posting it here.
Cheers.

**Comment by LinusBorg** [comment]
done

**Comment by mohitakahalo** [comment]
This works fine for the dev setup but messes up the production build process in the vue-cli. Getting this error on running "npm run build":

`ERROR in ./~/css-loader!./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/css-loader?{"minimize":true,"sourceMap":true}!./~/buefy/lib/buefy.css
Module build failed: Unknown word (5:1)

  3 | // load the styles
  4 | var content = require("!!../../css-loader/index.js?{\"minimize\":true,\"sourceMap\":true}!./buefy.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | if(content.locals) module.exports = content.locals;
  7 | // add the styles to the DOM
  8 | var update = require("!../../vue-style-loader/lib/addStylesClient.js")("0f433ac9", content, true);

 @ ./~/buefy/lib/buefy.css 4:14-186
 @ ./src/main.js`

**Comment by LinusBorg** [comment]
Ole a open a fresh issue
