### ISSUE TITLE
404 for js file being loaded via vue.js method

### ISSUE THREAD

**Issue by acollins1991** [vuejs-templates/webpack-simple#126]
I've got a method that should load a javascript file that is located within the assets folder, but the method keeps returning a 404 error. I'm certain I have the path correct so not sure why this isn't being found.

Method looks something like this:

```
methods: {
 runTest: function () {
  w = new Worker('./assets/script.js')
 }
}
```

**Comment by LinusBorg** [comment]
Sorry for the riduculously late answer:
```javascript
new Worker(require('./assets/script.js'))
```
