### ISSUE TITLE
Docs: configs must be double quoted

### ISSUE THREAD

**Issue by dfee** [vuejs-templates/webpack-simple#127]
I'm not clear on why, and this is likely a feature of webpack itself, but when defining environment variables in `config/dev.env.js` or its production counterpart, strings must be double quoted, e.g.:

```es6
module.exports = {
  GOOGLE_ANALYTICS_ID: '"GA-1234-1"',
  NODE_ENV: '"production"',
};
```

I'm not clear about why this is the case - why doesn't `GOOGLE_ANALYTICS_ID: 'GA-1234-1'` work?

**Comment by LinusBorg** [comment]
webpack's `DefinePlugin` inserts the value as-is into your code. it turns this:
```javascript
if (process.env.NODE_ENV === 'development')
```
into this:
```javascript
if ("production" === 'development')
```
If you leave out the double quotes, it turns into this:

```javascript
if (production === 'development')
```

...which will obviously cause an error - there's no variable called `production`.

**Comment by dfee** [comment]
Thanks!
