### ISSUE TITLE
how to use the sass loader with this 

### ISSUE THREAD

**Issue by Dsaint109** [vuejs-templates/webpack-simple#128]
Anytime I try using materialize.scss withthis i get an error
![wefds](https://user-images.githubusercontent.com/11745653/29765562-98b08d7c-8bd3-11e7-8e1f-157ca104a69e.PNG)

**Comment by connor11528** [comment]
When you first creat the project it asks if you would like to use sass, select yes. If you selected no and would like to add it follow these steps:

- install packages: `npm i node-sass sass-loader style-loader --save-dev`
- In your webpack file add the scss loader:

```
rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          loaders: {
            scss: 'style-loader!css-loader!sass-loader'
          }
          // other vue-loader options go here
        }
```
