### ISSUE TITLE
babel-loader: Module not found: Error: Can't resolve './Hello'

### ISSUE THREAD

**Issue by MikaelEdebro** [vuejs-templates/webpack-simple#130]
For some reason I can't import .vue files on a completly fresh `vue init webpack-simple folder`.
I can run `npm run dev` initially, but as soon as I try to import a .vue component, this error occurrs:
```
ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
Module not found: Error: Can't resolve './Hello' in 'C:\Projekt\test-simple\src'
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue 23:0-28
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```

I've tried:
* reinstalling multiple times
* clearing node_modules, npm cache, package-lock.json, and doing npm install
* updating to newer versions of babel npm packs

I can import regular ES2015 modules, but not .vue files. The ´webpack´ template works just fine. It's just ´webpack-simple` that this occurs for.

This is the entire chain of commands I ran:
```
PS C:\Projekt> node -v
v8.4.0
PS C:\Projekt> npm -v
5.3.0
PS C:\Projekt> vue init webpack-simple test-simple

? Project name test-simple
? Project description A Vue.js project
? Author xxx
? Use sass? No

   vue-cli · Generated "test-simple".

   To get started:

     cd test-simple
     npm install
     npm run dev.

PS C:\Projekt> cd .\test-simple\
PS C:\Projekt\test-simple> npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})

added 719 packages in 28.601s
PS C:\Projekt\test-simple> code .
PS C:\Projekt\test-simple> npm run dev

> test-simple@1.0.0 dev C:\Projekt\test-simple
> cross-env NODE_ENV=development webpack-dev-server --open --hot

Project is running at http://localhost:8080/
webpack output is served from /dist/
404s will fallback to /index.html
(node:8816) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https
://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Hash: 36d28f7f874921c7a344
Version: webpack 2.7.0
Time: 3602ms
                                    Asset     Size  Chunks                    Chunk Names
logo.png?82b9c7a5a3f405032b1db71a25f67021  6.85 kB          [emitted]
                                 build.js  1.69 MB       0  [emitted]  [big]  main
chunk    {0} build.js (main) 601 kB [entry] [rendered]
   [36] ./~/vue/dist/vue.esm.js 268 kB {0} [built]
   [38] (webpack)/hot/emitter.js 77 bytes {0} [built]
   [39] ./src/main.js 134 bytes {0} [built]
   [40] (webpack)-dev-server/client?http://localhost:8080 5.83 kB {0} [built]
   [41] (webpack)/hot/dev-server.js 1.57 kB {0} [built]
   [43] ./~/ansi-regex/index.js 135 bytes {0} [built]
   [52] ./~/loglevel/lib/loglevel.js 6.74 kB {0} [built]
   [85] ./~/strip-ansi/index.js 161 bytes {0} [built]
   [87] ./~/url/url.js 23.3 kB {0} [built]
   [89] ./src/App.vue 1.74 kB {0} [built]
   [95] (webpack)-dev-server/client/overlay.js 3.6 kB {0} [built]
   [96] (webpack)-dev-server/client/socket.js 856 bytes {0} [built]
   [98] (webpack)/hot nonrecursive ^\.\/log$ 160 bytes {0} [built]
   [99] (webpack)/hot/log-apply-result.js 1.02 kB {0} [built]
  [100] multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js 52 bytes {0} [built
]
     + 86 hidden modules

ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
Module not found: Error: Can't resolve './Hello' in 'C:\Projekt\test-simple\src'
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue 23:0-28
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```

**Comment by MikaelEdebro** [comment]
My App.vue script block. Hello.vue is in the same folder as App.vue:
```
<script>
import Hello from './Hello'
export default {
  name: 'app',
  data () {
    return {
      msg: 'Welcome to Your Vue.js App'
    }
  },
  components: {
      'hello': Hello
  }
}
</script>
```

**Comment by rosaWetteloos** [comment]
I've got the same problem. Were you able to figure this out?

**Comment by feats-choi** [comment]
you can try this for solution.
change your /project-directory/webpack.config.js to following setting (just add extensions)
```
resolve: {
    alias: {
      'vue$': 'vue/dist/vue.esm.js'
    },
    extensions: ['.js', '.vue', '.json']
},
```

**Comment by Utheau** [comment]
@feats-choi Thanks for the suggestion, it did work for me ;)

**Comment by feats-choi** [comment]
@Utheau 
Thanks, for your confirm~!
I also made a PR for this issue.
https://github.com/vuejs-templates/webpack-simple/pull/146
Hope will merge as soon as possible~

**Comment by letanure** [comment]
in my case was the diffference in text case on the import and the real tile name

wrong:
`index.js`
```
import SearchHistory from '@/store/modules/SearchHistory'
export default {
  SearchHistory,
}
...
```
real file name: `searchHistory.js`

locally on mac, works, but if I try to build on linux, I got the error

the trick part is, If I just change the filename 
> from `searchHistory.js` to `SearchHistory.js` 

_git_ will not get the change, so I need to change to another thing, like 

> from `searchHistory.js` to `_searchHistory.js`

 commit, and after this rename to 

> from `_searchHistory.js` to `SearchHistory.js`

**Comment by Tecayehuatl** [comment]
I was missing the dot before extension files lol

**Comment by Sovetnikov** [comment]
Little addition to someone who found this question.
On windows systems case of import name is ignored.
But on *nix systems case is important.
Issue maybe in wrong casing in import statement.

**Comment by me-jser** [comment]
> in my case was the diffference in text case on the import and the real tile name
> 
> wrong:
> `index.js`
> 
> ```
> import SearchHistory from '@/store/modules/SearchHistory'
> export default {
>   SearchHistory,
> }
> ...
> ```
> real file name: `searchHistory.js`
> 
> locally on mac, works, but if I try to build on linux, I got the error
> 
> the trick part is, If I just change the filename
> 
> > from `searchHistory.js` to `SearchHistory.js`
> 
> _git_ will not get the change, so I need to change to another thing, like
> 
> > from `searchHistory.js` to `_searchHistory.js`
> 
> commit, and after this rename to
> 
> > from `_searchHistory.js` to `SearchHistory.js`

it fixed my issue. thanks

**Comment by Manoj774** [comment]
try doing that code

**Comment by Manoj774** [comment]
esolve: {
    alias: {
      'vue$': 'vue/dist/vue.esm.js'
    },
    extensions: ['*', '.js', '.vue', '.json']
},

**Comment by toastsgithub** [comment]
> Little addition to someone who found this question.
> On windows systems case of import name is ignored.
> But on *nix systems case is important.
> Issue maybe in wrong casing in import statement.

@Sovetnikov Thanks, u just saved my day ...

**Comment by tianmarin** [comment]
> in my case was the diffference in text case on the import and the real tile name

Thank you @me-jser, this was a good hint; I realized that something on my Mac was OK, and not on Amplify, which uses Linux.


I was cheking for what seems an eternity... until checking very carefully in Terminal.
```
@/components/landscape_details/EnvironmentTable.vue
@/components/landscape_details/EnvironmentTable.Vue
```

Really thinking to dockerize my development environment so building errors would appear first locally.
