### ISSUE TITLE
DeprecationWarning: loaderUtils.parseQuery() received a non-string value...

### ISSUE THREAD

**Issue by COLABORATI** [vuejs-templates/webpack-simple#131]
Following the setup insctructions I get this error on `npm run dev`:
```
DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
```

**Comment by connor11528** [comment]
There are other threads about this [here](https://github.com/webpack/loader-utils/issues/56) and [here](https://github.com/vuejs/vue-loader/issues/666)

there are some fixes but it is only a warning and will go away soon
