### ISSUE TITLE
Please upgrade to wabpack 3

### ISSUE THREAD

**Issue by SteveCruise** [vuejs-templates/webpack-simple#132]
As the title

**Comment by iamdubx** [comment]
Webpack 3 has issues with vue-loader.

**Comment by timwis** [comment]
@iamdubx what issues? Can you link to a thread so I can follow along?

**Comment by iamdubx** [comment]
@timwis https://github.com/vuejs/vue-loader/issues/850

**Comment by ryanjaeb** [comment]
It looks like this was done in 0f95cb5.

**Comment by SteveCruise** [comment]
Thanks
