### ISSUE TITLE
How to disable minification and uglification?

### ISSUE THREAD

**Issue by d9k** [vuejs-templates/webpack-simple#137]
Hello!
How can I disable minification and uglification in resulting bundle altogether?
(It's required for debugging purposes. The resulting code is intended to run in special secured environment, not regular browser, and source mapping doesn't work as expected there)

**Comment by LinusBorg** [comment]
Remove/comment out  [this plugin](https://github.com/vuejs-templates/webpack-simple/blob/master/template/webpack.config.js#L67)
