### ISSUE TITLE
webpack-dev server not working in default setup (npm run dev)

### ISSUE THREAD

**Issue by benjhess** [vuejs-templates/webpack-simple#139]
Hi,

running "npm run dev" in a vanilla "webpack-simple" project does not work. The browser loads forever until a request timeout occurs. No personal firewall, no other service running on port 8080...

os: macos 10.12.5
node version: v6.11.3
npm version: 3.10.10
vue-cli version: 2.8.2

steps to reproduce:
```
sudo npm install -g vue-cli
mkdir simple-vue-project; cd simple-vue-project
vue init webpack-simple .
npm install
npm run dev
```

**Comment by benjhess** [comment]
Found the problem. It had nothing to do with the "webpack-simple" skeleton. It's really rather strange!

Using any other port worked, so i got curious. Starting any service on port 8080 and trying to reach it, yielded the same result. The app responsible for this is **Cisco AnyConnect Secure Mobile Client**. It seems to block all ingoing connections to port 8080. I had to deinstall the client, remove the **vpnagentd** service, and kill the process. Then it worked without any further issues. So if anyone runs into the same problem:

```
rm -rf /opt/cisco/anyconnect/bin/vpnagentd
killall vpnagentd
```

**Comment by jkobylec** [comment]
Hmm, I'm wondering if it's possible that dev server actually detects that the port is in use and chooses a different port--as the config/index.js comments indicate it's supposed to. But the "Your application is running here" message still shows the configured port rather than the one actually used at runtime?
