### ISSUE TITLE
eslint / airbnb error in template

### ISSUE THREAD

**Issue by francoisromain** [vuejs-templates/webpack-simple#14]
Hello, 

with ES lint / Airbnb styleguide, the [App.vue template](https://github.com/vuejs-templates/webpack-simple/blob/master/template/src/App.vue) makes an `unexpected token` error on the `{` on the second line: 

    export default {
        data () {
            return {
                …
            }
        }
    }

How is it possible to avoid this? 
Thank you
https://github.com/airbnb/javascript/issues/947

**Comment by chrisvfritz** [comment]
This template does not use ESLint, but you can see how it's implemented in the [webpack template](https://github.com/vuejs-templates/webpack/blob/dist/template/.eslintrc.js) for a reference.
