### ISSUE TITLE
Error when running npm run dev: Unexpected token '#' at 22:7 npm ERR! {{#sass}}

### ISSUE THREAD

**Issue by bnjmnmyers** [vuejs-templates/webpack-simple#141]
Please forgive me up front. I am new to npm and all things package.json/webconfig.

When I download project and have gone through all of the steps and then I do "npm run dev"
I get the following error:

> npm ERR! file /Users/myersb/DEV/vue-cli/package.json
> npm ERR! code EJSONPARSE
> npm ERR! Failed to parse json
> npm ERR! Unexpected token '#' at 22:7
> npm ERR!     {{#sass}}
> npm ERR!       ^
> npm ERR! File: /Users/myersb/DEV/vue-cli/package.json
> npm ERR! Failed to parse package.json data.
> npm ERR! package.json must be actual JSON, not just JavaScript.
> npm ERR!
> npm ERR! Tell the package author to fix their package.json file. JSON.parse
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/myersb/.npm/_logs/2017-10-05T18_23_37_349Z-debug.log

I'm certain that {{#sass}} and {{/sass}} in the package.json and webpack.config.js are probably some things that I'm supposed to change, but like I said I'm so new to this that I just don't know where to begin.

I did try removing those lines from each and after that I am able to successfully run "npm run dev" but then the styling, that is by default in the App.vue, doesn't seem to actually work.

Any help you can offer is greatly appreciated.

**Comment by Tribex** [comment]
@bnjmnmyers Your issue is that you're downloading this repository directly. This repository is a `template` for [vue-cli](https://github.com/vuejs/vue-cli). The files are not to be used directly since they contain various metadata and switches such as the one you're encountering.

Anyway, to successfully use this template, install [vue-cli](https://github.com/vuejs/vue-cli) globally via. `NPM`:

```bash
$ npm install -g vue-cli
```

Then create a new project using:
```bash
$ vue init webpack-simple my-project-name
$ cd my-project-name
$ npm install
```

Answer "Yes" (`Y`) when the prompt asks you if you wish to use SASS.

Then you should be all set!

**Comment by bnjmnmyers** [comment]
@Tribex, thanks for the response. I did try that but our firewall where I work doesn't seem to want to let me do that. When I run the vue init command I get the following error:

> vue-cli · Failed to download repo vuejs-templates/webpack-simple: unable to get local issuer certificate

**Comment by Tribex** [comment]
@bnjmnmyers Ouch, of all the things that could happen...

Anyway, I went ahead and ran the `vue init` command on my computer to generate an example project for you, if that could be helpful.

I'm not sure what your work's policy is on downloading zip files from random people on the internet, but here it is anyway if it helps.
Configured with SASS enabled.
[Example Template.zip](https://github.com/vuejs-templates/webpack-simple/files/1370491/Example.Template.zip)

**Comment by bnjmnmyers** [comment]
@Tribex, you know they would much rather me download from a random stranger than pull it from a public repository :D *smh*. Thanks by the way.

**Comment by Tribex** [comment]
@bnjmnmyers Ouch, I feel kind of sorry for you. :cry: 

Glad to help out, good luck!
