### ISSUE TITLE
Error in webpack config

### ISSUE THREAD

**Issue by samokoder** [vuejs-templates/webpack-simple#151]
`npm run dev` fails with

```
C:\prj\vuejs\test\node_modules\webpack-dev-server\bin\webpack-dev-server.js:388
    throw e;
    ^

Error: options/query provided without loader (use loader + options) in {
  "test": {},
  "use": "vue-loader",
  "options": {
    "loaders": {}
  }
}
```

I'm using default webpack config from template
[webpack.config.js](https://pastebin.com/xt85Ee0C)
[package.json](https://pastebin.com/pKnuJ3gS)

**Comment by mikebonds** [comment]
Getting the exact same error...

**Comment by LinusBorg** [comment]
Fixed, sorry folks, I was lazy, wont happen again.
