### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by joannesalfa** [vuejs-templates/webpack-simple#153]
I followed the commands below:

`vue init webpack-simple`
with **sass enabled**

then I rewrote the dependencies:

```
  "dependencies": {
    "buefy": "^0.5.4",
    "firebase": "^4.6.1",
    "flag-icon-css": "^2.8.0",
    "vue": "^2.4.4",
    "vue-i18n": "^7.3.2",
    "vue-router": "^3.0.1",
    "vuefire": "^1.4.4",
    "vuex": "^3.0.1"
  },
```

then

`npm install`

finally,

`npm run dev`

and I got error:

[https://i.imgur.com/io7Gote.png](https://i.imgur.com/io7Gote.png)

**Comment by joannesalfa** [comment]
similiar to this error

https://github.com/webpack/webpack-dev-server/issues/940

**Comment by joannesalfa** [comment]
I found another error related to css-loader

you may test with vue init webpack-simple with sass enabled and do npm install and npm run dev


`I found another error
C:\Users\Black Puma\Desktop\exportmaker\project\EXPORTMAKER\webpack.config.js:58
              'css-loader',
              ^^^^^^^^^^^^
SyntaxError: Unexpected string
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireConfig (C:\Users\Black Puma\Desktop\exportmaker\project\EXPORTMAKER\node_modules\webpack\bin\convert-argv.js:97:18)
css-loader`

**Comment by joannesalfa** [comment]
You trolled us...

[discord screenshot](https://i.imgur.com/sg5R7zk.png)

**Comment by joannesalfa** [comment]
also without sass... come on this template is broken...

`C:\Users\Black Puma\Desktop\exportmaker\project\test\node_modules\webpack-dev-server\bin\webpack-dev-server.js:388
    throw e;
    ^

Error: options/query provided without loader (use loader + options) in {
  "test": {},
  "use": "vue-loader",
  "options": {
    "loaders": {}
  }
}
``

**Comment by bktp** [comment]
Replace all the "use" keys with "loader"/"loaders". Worked for me.

**Comment by LinusBorg** [comment]
Yeah I screwed up because I was lazy, already on it ... Sorry :/

**Comment by joannesalfa** [comment]
@LinusBorg I wasted my hours to figure out the error, I was unable to work, it would be nice if you add separate 2 templates:

webpack-simple  = stable
webpack-simple-beta = unstable and lazy

what are you kind of front end hacker who never tests your last commit?

**Comment by LinusBorg** [comment]
fixed.

**Comment by joannesalfa** [comment]
@LinusBorg Thank you! 💃
