### ISSUE TITLE
css-loader are broken again

### ISSUE THREAD

**Issue by joannesalfa** [vuejs-templates/webpack-simple#154]
In my main.js, I installed with 2 css libraries in node_modules

My snippets are:

```
import 'buefy/lib/buefy.css'
import 'flag-icon-css/css/flag-icon.css'
```

and I got an error

[screenshot](https://i.imgur.com/tUFZSy1.png)

Yesterday, it was working fine before your latest commit...

**Comment by heydarli** [comment]
I think removing second css loader from webpack config files should fix this.
