### ISSUE TITLE
...mapState from vuex not working

### ISSUE THREAD

**Issue by ianengelbrecht** [vuejs-templates/webpack-simple#157]
It seems as though the webpack config doesn't support the object spread operator. I had to reinstall devDependencies, and update .babelrc to the following:

{
    "presets": [
        ["es2015", { "modules": false, "loose": true}],
        ["stage-2"]
    ],
    "plugins": [
        ["transform-runtime"],
        ["transform-object-rest-spread"],
        ["transform-es2015-destructuring"]
    ]
}

However, now I get this error on compilation:

__webpack_require__(...) is not a function.

It would be fantastic if this template could support vuex's ...mapState out of the box, rather than having to the move to the full webpack template.

**Comment by LinusBorg** [comment]
That's been fixed, you seem to run on an older version of the template, we [added `babel-preset-stage-3` 5 months ago](https://github.com/vuejs-templates/webpack-simple/blame/bd8a372db5a6a76b075b0641df2c2a8309ce6ed4/template/.babelrc#L4), which [includes](https://babeljs.io/docs/plugins/preset-stage-3/) `babel-transform-object-rest-spread`.
