### ISSUE TITLE
Different setups for webpack-simple and webpack for resolve.extensions

### ISSUE THREAD

**Issue by MichaelFromin** [vuejs-templates/webpack-simple#164]
If I make a new project based on webpack I get a resolve.extensions section like this:

```
resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
      '@': resolve('src'),
    }
  }
```

If I use the webpack-simple template I get this:

```
resolve: {
  alias: {
    'vue$': 'vue/dist/vue'
  }
}
```

Note that the setup for webpack-simple does not include .vue templates so when you import them you have to explicitly include the .vue on the end of the import. 

Is there a reason for this omission? Most IDEs will remove the .vue when you import the file so it seems odd to not include this in the resolve setup.

**Comment by MichaelFromin** [comment]
Apparently I had an old template ... this appears to be fixed already.  Apologies.

**Comment by LinusBorg** [comment]
then close the issue ;)
