### ISSUE TITLE
404s will fallback to /index.html

### ISSUE THREAD

**Issue by Helg18** [vuejs-templates/webpack-simple#174]
I use it from docker.

npm run dev return this 

Project is running at http://localhost:8080/
webpack output is served from /dist/
404s will fallback to /index.html

npm -v  -> 5.6.0

On 172.17.0.2/project is empty.

**Comment by Helg18** [comment]
This issue is solved time ago.

From docker, webpack had conflicts because I was using the same port between docker and webpack.

**Comment by ankitAMD** [comment]
how you can solve this  error ? Are you trying to setup iot based project people-counter ? could you explain tha twith proper examples
