### ISSUE TITLE
访问地址 localhost  改为ip 无法访问

### ISSUE THREAD

**Issue by senyawang** [vuejs-templates/webpack-simple#25]
vue-cli 起的服务 是localhost:8080    为什么我把localhost 换成我的ip就访问 不了了呢， 访问localhost:8080 就一切正常

**Comment by phoenixgao** [comment]
127.0.0.1?

**Comment by kbqncf** [comment]
更改host文件，localhost指向你的本机ip

**Comment by arliang** [comment]
在`devServer`中添加`host: '0.0.0.0'`就行了，不过在启动的时候会打开`http://0.0.0.0:8080`
更多参数配置可以查看[DevDocs - Webpack 2 - DevServer](http://devdocs.io/webpack~2/configuration/dev-server/index)

**Comment by kazupon** [comment]
Close (in-activity)

**Comment by tianyou6842** [comment]
我在装lavadock时也发生同样问题。结果我发现我的Chrome装了Proxy swithysharp扩展，然后我把我的IP直接写进“不代理的地址”列表，问题就解决了。你是不是也使用了代理呢？

**Comment by SilenceZeng** [comment]
build/dev-server.js中：
`var server = app.listen(port, 'localhost')`
改为：
`var server = app.listen(port)`
或
`var server = app.listen(port, '0.0.0.0')`

**Comment by allinshang** [comment]
11月13使用最新的vue init webpack myproject构建项目，发现build/下边没有了dev-server.js文件，出
现了这个问题。
解决方法：
build/webpack.dev.conf
//host: process.env.HOST || config.dev.host,
host: '0.0.0.0',

**Comment by jianxiaoBai** [comment]
我是这样做的
![image](https://user-images.githubusercontent.com/20953838/34186689-3b5a92e6-e568-11e7-90b5-ec42a9378c0b.png)
