### ISSUE TITLE
 in '$npm run dev' display image,do not display at build

### ISSUE THREAD

**Issue by XiaoYiS** [vuejs-templates/webpack-simple#31]
<img src="./../images/xxx.png"> in run build is not show,css:background-img:(url="./../xxx.png") is show,in dev show all

**Comment by Iamie6** [comment]
webpack.config.js   publicPath:'./dis/'

**Comment by XiaoYiS** [comment]
i just do it  publicPath: './dist/',

**Comment by kazupon** [comment]
Close (in-acitivty)
