### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by luolala** [vuejs-templates/webpack-simple#33]
when npm run dev get error like this:
getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
how can i fix it?

**Comment by kaihendry** [comment]
Add localhost to your `/etc/hosts`? Find another computer with sane default networking? :)

**Comment by luolala** [comment]
yes,I set 127.0.0.1 localhost in my Switchhosts,and then it works~but why should i set this?

**Comment by kaihendry** [comment]
It's an assumed convention I guess. Every computer has this by default and I guess you accidentally removed it?

**Comment by luolala** [comment]
yes,I found there is no localhost in my /etc/hosts,maybe I removed it accidentally ,thanks a lot~

**Comment by chrisvfritz** [comment]
This looks resolved.
