### ISSUE TITLE
npm run dev doesn't work

### ISSUE THREAD

**Issue by pedro-mass** [vuejs-templates/webpack-simple#36]
Tried booting up the base app structure to see it running. Did an npm install, and ran npm run dev; but the webpage it brings up says that it can't reach localhost.

If i run the full webpack, instead of webpack-simple, the same steps bring up a working page.

Am I missing something?

**Comment by yyx990803** [comment]
Maybe a problem with `webpack-dev-server`... the full `webpack` template uses a custom express server.

**Comment by tbreuss** [comment]
I had the same issue with this and other vuejs-templates, too.

The problem in my case was another service (Jenkins CI) using default port number "8080".

So, you probably can fix this by editing line 8 in `package.json`:

    "serve": "http-server -o -s -c 1 -a localhost -p 8088",

Give it a try.

**Comment by pedro-mass** [comment]
Nope. I tried port 3000 before posting

**Comment by pedro-mass** [comment]
Here's some of the output.

`> webpack-simple@ dev /Users/sparcfloater/dev/learn/vue.js/vue-cli/webpack-simple
> cross-env NODE_ENV=development webpack-dev-server --open --inline --hot --port 3000

 http://localhost:3000/
webpack result is served from /dist/
404s will fallback to /index.html`

I've run 'npm run build', noticed the index.html isn't copied over. So I copied that over to see if it fixes the issue. No luck though.

**Comment by li3p** [comment]
I run `npm update` in a project which using `webpack-simple` as skeleton today. and got following errors after run `npm run dev`:

```
ERROR in multi main
Module not found: Error: Can't resolve 'babel' in 'xxxx/xxx/xxx/unicon'
 @ multi main
```

It kept report such errors even I create a whole new project via `vue init webpack-simple unicon`.

My environment:
node -v
v7.1.0
npm -v
3.10.9

**Comment by chrisvfritz** [comment]
@pedro-mass Could you share your OS and node version?

**Comment by pedro-mass** [comment]
@chrisvfritz 
OS: OSX v10.11.6 El Capitan
node: v6.9.1

**Comment by pedro-mass** [comment]
Fixed. For some reason my localhost was set to ::1.

**Comment by ogz00** [comment]
@pedro-mass how did you solve this, I have same issue here. Thanks

**Comment by ekmlarbi** [comment]
@pedro-mass, "::1" is the localhost representation in ipv6. You should have both 
> 
127.0.0.1       localhost
::1             localhost

in your /etc/hosts file. This means you will have to use 127.0.0.1 to refer to **localhost** in ipv4. You can delete/comment out the ::1 anyway too to avoid the conflict, its fine.

**Comment by fatihcandev** [comment]
> Fixed. For some reason my localhost was set to ::1.

did you delete that ::1 line or just changed it?
