### ISSUE TITLE
加入UI框架element-ui时，会报错，始终没办法

### ISSUE THREAD

**Issue by qw789** [vuejs-templates/webpack-simple#51]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue2@~predev: vue2@
6 silly lifecycle vue2@~predev: no script for predev, continuing
7 info lifecycle vue2@~dev: vue2@
8 verbose lifecycle vue2@~dev: unsafe-perm in lifecycle true
9 verbose lifecycle vue2@~dev: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\vue2-example-master2\vue2-example-master\node_modules\.bin;C:\Users\qw\bin;C:\Program Files (x86)\Git\mingw32\bin;C:\Program Files (x86)\Git\usr\local\bin;C:\Program Files (x86)\Git\usr\bin;C:\Program Files (x86)\Git\usr\bin;C:\Program Files (x86)\Git\mingw32\bin;C:\Program Files (x86)\Git\usr\bin;C:\Users\qw\bin;C:\Program Files (x86)\Common Files\NetSarang;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs;C:\Users\qw\AppData\Local\atom\bin;C:\Users\qw\AppData\Local\Microsoft\WindowsApps;C:\Users\qw\AppData\Roaming\npm;C:\Program Files (x86)\Git\usr\bin\vendor_perl;C:\Program Files (x86)\Git\usr\bin\core_perl
10 verbose lifecycle vue2@~dev: CWD: D:\vue2-example-master2\vue2-example-master
11 silly lifecycle vue2@~dev: Args: [ '/d /s /c', 'webpack-dev-server --open --inline --hot' ]
12 silly lifecycle vue2@~dev: Returned: code: 1  signal: null
13 info lifecycle vue2@~dev: Failed to exec dev script
14 verbose stack Error: vue2@ dev: `webpack-dev-server --open --inline --hot`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid vue2@
16 verbose cwd D:\vue2-example-master2\vue2-example-master
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v6.9.2
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error vue2@ dev: `webpack-dev-server --open --inline --hot`
22 error Exit status 1
23 error Failed at the vue2@ dev script 'webpack-dev-server --open --inline --hot'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the vue2 package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server --open --inline --hot
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs vue2
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls vue2
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by kazupon** [comment]
Close (inactivity)
