### ISSUE TITLE
Assets pathing issue

### ISSUE THREAD

**Issue by Heydon** [vuejs-templates/webpack-simple#53]
Hi,

When I put assets in the `assets` folder and reference them like

```html
<a href="./assets/sound.mp3">sound file</a>
```

they don't convert in build (to `/build/sound.mp3?8273t83rt72tr3etc`).

Instead, I get a "cannot GET [file]" warning printed to screen.

I tried reconfiguring vue-loader but nothing seemed to work.

For example, I tried placing mp3 in 

```js
      {
        test: /\.(png|jpg|gif|svg|mp3)$/,
        loader: 'file-loader',
        options: {
          name: '[name].[ext]?[hash]'
        }
      }
```

but this only helps me make dist `src` paths for images to mp3 files, which obviously isn't what I want 😆.

Sorry if this is a silly question 😬

**Comment by Heydon** [comment]
Now tried `url-loader`, but that doesn't work either.

```js
      {
        test: /\.mp3$/,
        loader: 'url-loader',
        query: { mimetype: 'audio/mpeg' }
      }
```

**Comment by LinusBorg** [comment]
> but this only helps me make dist src paths for images to mp3 files, which obviously isn't what I want

Uhm, no.

That should actually work.

**Comment by Heydon** [comment]
@LinusBorg Welp, never mind.

**Comment by LinusBorg** [comment]
To be clear, what I mean is that this loader is not reserved for images. It's hair the most common asset so the default file extensions are all images. It works for all kinds of assets though.
