### ISSUE TITLE
Missing sass dependencies in the package.json?

### ISSUE THREAD

**Issue by fabd** [vuejs-templates/webpack-simple#55]
The webpack config mentions scss and sass loaders for the .vue files, but the package.json does not mention it.

Installed node-sass and sass-loader to solve a `<style lang="scss">` in a vue component, although I don't know if that's the correct solution (beginner here).

```
$ npm install node-sass --save-dev
$ npm install sass-loader --save-dev
```

It may seem obvious but it's not to me. For example I wonder if there are smaller packages to keep node_modules/ as lean as possible, since I only use sass/scss in vue files atm. I am also wondering if it's my config which is faulty causing webpack to fail (perhaps something else can handle sass?).

**Comment by chatii2412** [comment]
read this: https://github.com/vuejs-templates/webpack/blob/3225018bc1455219efa4f517aacf97f256d81fc9/docs/pre-processors.md

**Comment by AnnieManu** [comment]
This command  npm install sass-loader --save-dev seemed to solve my problem, Thank you)
