### ISSUE TITLE
Can't get webpack dev server to run

### ISSUE THREAD

**Issue by ttmjason** [vuejs-templates/webpack-simple#6]
I followed the steps in the README up until "npm run dev". I did not add any extra packages and have the latest version of Node and NPM on OSX 10.10.5. It returns this error output:

```
> webpackTest@ dev /Users/jason/Sites/webpackTest
> webpack-dev-server --inline --hot

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at net.js:1376:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v5.8.0
npm ERR! npm  v3.8.2
npm ERR! code ELIFECYCLE
npm ERR! webpackTest@ dev: `webpack-dev-server --inline --hot`
npm ERR! Exit status 1
```

**Comment by yyx990803** [comment]
It seems you have another process already using the 8080 port.

**Comment by ttmjason** [comment]
Well dang, there's nothing running on 8080, so I'll have to investigate elsewhere. Thanks anyway.

**Comment by chrisvfritz** [comment]
@ttmjason It's probably a previous process that didn't shut down properly. On OS X, you can run this to see a list of processes bound to a port: 

```
lsof -iTCP -sTCP:LISTEN -n -P
```

**Comment by ttmjason** [comment]
That's a great command I'm saving away. I ended up restarting my Terminal since I knew there were any critical processes running and instead I got:

`http://localhost:8080/
webpack result is served from /dist/
content is served from /Users/jason/Sites/webpackTest
404s will fallback to /index.html`

And nothing on http://localhost:8080

**Comment by brandonk3nt** [comment]
Having the same issue even after closing all terminal windows and re-starting on just one. The only workaround is to delete `node_modules` then re-install all of them. Kind of crappy but it works. Seems to be an issue with webpack-dev-server if anything.

**Comment by brandonk3nt** [comment]
^^^
```
rm -rf node_modules
``` 
BTW
