### ISSUE TITLE
Resolving paths in webpack on Windows

### ISSUE THREAD

**Issue by afterburn** [vuejs-templates/webpack-simple#60]
```
ERROR in ./src/App.vue
Module not found: Error: Cannot resolve module 'D:ProjectName
ode_modulesue-loaderlibcomponent-normalizer' in D:\ProjectName\src
 @ ./src/App.vue 5:16-88
```

Weird path resolving stuff happens when using this boilerplate on Windows.
I'm using Node v7.3.0.

**Comment by protocol114** [comment]
I've got the same thing, was on Node v6.9.1 and upgraded to v7.4.0 and still receiving a similar error. I have made no changes to the project, and have only run "npm install" and "npm run dev".

**Comment by jsteacat** [comment]
+ I have the same problem

**Comment by evorine** [comment]
Unfortunately I have the same problem :(

**Comment by gihanr** [comment]
Getting same error.. :(

**Comment by afterburn** [comment]
Gentle bump, anyone managed to get it working?

**Comment by protocol114** [comment]
I'm not sure if everyone has tried yet, but it looks like vue-loader was updated to 10.2.3 and everything is working well for me now.

I'm not 100% sure if the vue-loader update actually solved the issue, but all seems well.

**Comment by jsteacat** [comment]
Yes, it worked))

**Comment by afterburn** [comment]
Initializing this scaffold through the vue-cli instead of cloning it from GitHub got it working for me for a reason unknown to me, maybe it's due to what @protocol114 mentioned.
