### ISSUE TITLE
Is this project still "not suitable for production", and is there a suitable alternative?

### ISSUE THREAD

**Issue by matthewpennell** [vuejs-templates/webpack-simple#61]
The README states:

> Note this template is not suitable for production - for that you may want to wait for an official 2.0 webpack template.

Is that statement still true? What is the recommended alternative for a webpack/loader based Vue project? [vue-loader](https://github.com/vuejs/vue-loader) just points to this repo. Is [vuejs-templates/webpack](https://github.com/vuejs-templates/webpack) the most appropriate starting point for projects intended for production?

**Comment by kazupon** [comment]
Yes, We hope you'll use `vuejs-templates/webpack`. 
`vuejs-templates/webpack` is mainly used for quick  prototyping.
