### ISSUE TITLE
Simplify configuration by using `vue-cli build`

### ISSUE THREAD

**Issue by xpepermint** [vuejs-templates/webpack-simple#62]
Please replace the current configuration (webpack, scripts, babel) with https://github.com/vuejs/vue-cli/releases/tag/v2.8.0 (`vue build`).

Example:
```js
  "scripts": {
     ...
    "build": "vue build src/index.js --prod --lib --config ./vue.config.js"
  },
```

**Comment by egoist** [comment]
I can see the benifit of this since we already have `webpack` template for larger project. 

/cc @LinusBorg

**Comment by egoist** [comment]
I created another template instead https://github.com/egoist/template-vue, maybe close this.

**Comment by xpepermint** [comment]
thx
