### ISSUE TITLE
ReferenceError on hot update: cssModules is not defined

### ISSUE THREAD

**Issue by regularmike** [vuejs-templates/webpack-simple#63]
I just created a new webpack-simple project and was able to load the index.html page, but when I changed the `msg` property in the data function in App.vue by just adding an exclamation point to the end I got this error in the console when it attempted hot module replacement. I didn't change anything else. Another user on vue Gitter channel was also able to reproduce just now.

Uncaught ReferenceError: cssModules is not defined
    at eval (eval at <anonymous> (build.js:1009), <anonymous>:34:23)
    at hotApply (build.js:501)
    at hotUpdateDownloaded (build.js:285)
    at hotAddUpdateChunk (build.js:265)
    at webpackHotUpdateCallback (build.js:8)
    at 0.b6ea842….hot-update.js:1

**Comment by unclejustin** [comment]
I can also recreate from a clean install.

**Comment by regularmike** [comment]
Update: this is definitely a new bug. Several users have been able to reproduce. I asked about it in the forums and (´・ω・｀) was able to reproduce and said they would try to fix. I've reproduced on different machines with webpack-simple as well as webpack templates.

**Comment by regularmike** [comment]
I can fix this for now by rolling back to these:

"webpack": "^2.1.0-beta.25",
"webpack-dev-server": "^2.1.0-beta.0"

**Comment by regularmike** [comment]
Hey @TheLarkInn, thanks for tweeting with me about this. Also spoke to @HerringtonDarkholme in the Vue Forum, who was able to reproduce and said they would try to fix, so it may not need your input, but feel free to review of course. I'm primarily concerned because I've recorded a video tutorial that follows the steps in the documentation in the beginning, but I faked it by rolling back the two packages mentioned above. Won't be published for a while but it would also be great if users who are new to vue-cli and coming here today don't encounter it.

**Comment by HerringtonDarkholme** [comment]
The fix for Vue loader has been published! 
The template should work now.
Cheers!

**Comment by regularmike** [comment]
@HerringtonDarkholme confirmed! Thanks a lot for the quick fix. This is a great way to show someone the power of single-file components and webpack.

**Comment by kazupon** [comment]
Close (Fixed)
