### ISSUE TITLE
"unexpected strict mode reserved word" error throwed in Android 4.0.4

### ISSUE THREAD

**Issue by arliang** [vuejs-templates/webpack-simple#66]
In Android 4.0.4 webview it shows a blank page

When I add these code as the first child of `<body>`, it alerts `unexpected strict mode reserved word`

```html
    <script type="text/javascript">
      window.onerror = function(e){
        alert(e) // unexpected strict mode reserved word
      }
    </script>
```

This problem solved by removing all `'use strict';`

I'd like to know if there is another way to solve this problem.

**Comment by yellowlemon** [comment]
me too, you had another solve way?

**Comment by LinusBorg** [comment]
`window.alert`
