### ISSUE TITLE
Module scss/sass not found

### ISSUE THREAD

**Issue by victorsilent** [vuejs-templates/webpack-simple#70]
I'm trying to load one scss file at App.vue using:
`<style src="assets/style.scss" lang="scss"></style>`
but i'm getting this error: 
`./src/App.vue Module not found: Error: Can't resolve 'assets/style.scss'`
I have install sass-loader, node-sass, update my npm (4.2.0), node (6.4.0) and the error continues =/
The only change that I've made after install all these libs is add src="assets..." on my App.vue

**Comment by zcong1993** [comment]
make sure your answer of  inquire question of **sass** option is yes when init template, default is false 

it work well for me when answer yes

**Comment by victorsilent** [comment]
Thank you, but I solved the problem adding `scss: 'vue-style-loader!css-loader!sass-loader'` on my webpack loaders

**Comment by zcong1993** [comment]
the template will add sass loader only when the sass option is yes.

so if you set it yes when asked,  you will not need add the loaders by yourself
