### ISSUE TITLE
"Note this template is not suitable for production" - care to elaborate why?

### ISSUE THREAD

**Issue by tonylampada** [vuejs-templates/webpack-simple#79]
I love the simplicity of this webpack setup as compared to the "full" webpack template.

The readme says "not suitable for production" but doesn't explain why. I'd love to know what exactly would be the minimum change that should be made to make it ready for production. Maybe there should be a link on the readme pointing to that information.

**Comment by LinusBorg** [comment]
Well, it is suitable for production if your app is a small and quite simple one. It's not "unstable" or anything

But usually, for a bigger app (aside from the fact that this template doesn't come with any testing tools),  you would usually:

* Extract CSS into a seperate file
* Exract libs you used (e.v. Vue) into a separate vendor chunk (so it can be cached even when you update your app. This can be further optimized.)
* Config webpack to handle webfonts correctly

All of this can be *added* to this template, but it doesn't include it.

**Comment by tonylampada** [comment]
Excellent, thanks a bunch!
