### ISSUE TITLE
Localhost:8080 doesn't show anything

### ISSUE THREAD

**Issue by ttmjason** [vuejs-templates/webpack-simple#8]
On Mac OSX 10.10.5 Yosemite, `npm run dev` does not seem to work. This is an out of the box installation. The Vuejs template "webpack" works just fine. I double checked and nothing else is running on port 8080. Chrome browser shows this:

**The localhost page isn’t working

localhost didn’t send any data.
ERR_EMPTY_RESPONSE**

while the Terminal output from the npm command shows this:

` webTEST@ dev /Users/jason/Sites/webTEST
 webpack-dev-server --inline --hot

http://localhost:8080/
webpack result is served from /dist/
content is served from /Users/jason/Sites/webTEST
404s will fallback to /index.html`

**Comment by ttmjason** [comment]
I also ran `rm -rf node_modules/` and then `npm install` just to make sure nothing was installed weirdly and had the same issue.

**Comment by yyx990803** [comment]
What's your node/npm version?

**Comment by ttmjason** [comment]
Node: 5.8.0
npm: 3.8.2

I have this particular issue solved, though hot reload still doesn't work.

First thing I had to do was turn off MAMP- I had it running for other reasons on port 8888 and that seemed to mess things up. That didn't complete the fix- I also have to add 

`--port 3000`

to the dev script in the package.json and then it started working. However, changing something in the data and saving won't trigger a reload even though I have `--inline -hot` in the npm run dev script.

**Comment by chrisvfritz** [comment]
Changing data doesn't trigger a hot reload because it only contains _initial_ state for the component. So changing it has no effect once the component is mounted. Is hot reload working in other cases, such as when changing a computed value or something in the template?
