### ISSUE TITLE
[improvement] Use arrays instead of exclamation mark separated string for loaders

### ISSUE THREAD

**Issue by wujekbogdan** [vuejs-templates/webpack-simple#82]
It would be better if you used a new syntax, introduced in webpack2 - arrays instead of exclamation mark separated string. It's cleaner, looks more standard (especially for beginners) and it's less error prone.

So instead of:
``` javascript
loaders: {
    'scss': 'vue-style-loader!css-loader!sass-loader',
}
```
Use: 
``` javascript
loaders: {
    'scss': [
        'vue-style-loader',
        'css-loader',
        'sass-loader'
    ]
}
```

**Comment by LinusBorg** [comment]
Open to a PR :)

**Comment by chris-dura** [comment]
@LinusBorg I'm not a webpack config ninja, but I seem to be getting errors based on your https://github.com/vuejs-templates/webpack-simple/commit/3d93d83bb926621c3971e27db0520b20203ba0fb commit.
I'm guessing there's a syntax problem?

**Comment by LinusBorg** [comment]
Yep. Just fixed it. I tried to hack it in quickly, was too sure of my webpack knowledge. Won't happen again.
