### ISSUE TITLE
vue-style-loader ?

### ISSUE THREAD

**Issue by klevron** [vuejs-templates/webpack-simple#85]
Hello

Actually it is not possible to run this template since there's a missing dependency : `vue-style-loader`

> $ npm run dev
> ...
> ERROR in ./src/App.vue
> Module not found: Error: Can't resolve 'vue-style-loader' in '/home/ubuntu/workspace/vuejs-test/src'

After installing it with `npm install vue-style-loader --save-dev`, everything is fine.

**Comment by LinusBorg** [comment]
vue-style-loader is a dependency of vue-loader, so it will be installed.

I would guess that you use an outdated version of npm ( 2.*), which doesn't install dependencies in a flat folder structure.

**Comment by klevron** [comment]
The problme was not npm version, but node version, updating to 4.7 fix the problem.
